# Generated by Django 5.2.4 on 2025-09-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_bulk_update_prices', 'Can bulk update prices'),)},
        ),
    ]
