# Generated by Django 5.2.4 on 2025-09-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product_alter_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_fulfill_order', 'Can mark orders as Fulfilled'), ('can_cancel_order', 'Can cancel any order'), ('can_view_reports', 'Can view sales reports'))},
        ),
    ]
